// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBICZ4-CUiJ0oBJLsFbcqNRwJavcXusw80',
    appId: '1:410301120695:android:9015741fafae659a238d32',
    messagingSenderId: '410301120695',
    projectId: 'brainmaster-837c7',
    storageBucket: 'brainmaster-837c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpgDrmZ5tLz7JVExD3f646gII4zeZR0PE',
    appId: '1:410301120695:ios:6dd5c529670cabd0238d32',
    messagingSenderId: '410301120695',
    projectId: 'brainmaster-837c7',
    storageBucket: 'brainmaster-837c7.appspot.com',
    iosBundleId: 'com.example.brainMaster',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChyaY7-b2dp1LbfXR9wV1iXX3sfAoddhA',
    appId: '1:410301120695:web:1a83ba9d82ebc517238d32',
    messagingSenderId: '410301120695',
    projectId: 'brainmaster-837c7',
    authDomain: 'brainmaster-837c7.firebaseapp.com',
    storageBucket: 'brainmaster-837c7.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpgDrmZ5tLz7JVExD3f646gII4zeZR0PE',
    appId: '1:410301120695:ios:6dd5c529670cabd0238d32',
    messagingSenderId: '410301120695',
    projectId: 'brainmaster-837c7',
    storageBucket: 'brainmaster-837c7.appspot.com',
    iosBundleId: 'com.example.brainMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChyaY7-b2dp1LbfXR9wV1iXX3sfAoddhA',
    appId: '1:410301120695:web:283adbd838409832238d32',
    messagingSenderId: '410301120695',
    projectId: 'brainmaster-837c7',
    authDomain: 'brainmaster-837c7.firebaseapp.com',
    storageBucket: 'brainmaster-837c7.appspot.com',
  );

}